command:
  - uvicorn
  - main:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

env:
  - name: LAKEBASE_HOST
    value: "ep-snowy-bird-d2ok41nc.database.us-east-1.cloud.databricks.com"
  - name: LAKEBASE_PORT
    value: "5432"
  - name: LAKEBASE_DB
    value: "databricks_postgres"
  - name: LAKEBASE_ENDPOINT
    value: "projects/loyalty-engine/branches/production/endpoints/primary"
  - name: DATABRICKS_HOST
    value: "https://fevm-tko27-filipe.cloud.databricks.com"
